### ISSUE TITLE
error running setup.py

### ISSUE THREAD

**Issue by abfleishman** [riggsd/guano-py#18]
I am trying to run `python setup.py develop` and I am getting the error below.  I assume I have some issue with my environment, but I was able to run it after deleting the content of `README.rst` so maybe a bug?
![image](https://user-images.githubusercontent.com/9219852/64719441-1c299b00-d47d-11e9-82e0-5466583ce753.png)

**Comment by riggsd** [comment]
@abfleishman I believe I've fixed this in 2283051, are you able to test with `master` branch to verify?

(I don't have access to a Windows machine to confirm)

**Comment by abfleishman** [comment]
Gosh! This issue was from so long ago I forgot all about it!  I just cloned and ran `python setup.py develop` without issue.  I am on a windows 10 "home edition" laptop so I assume that the issue is fixed.  Thanks!

**Comment by riggsd** [comment]
Sorry this slipped under my radar, and I appreciate the report and confirmation!
